version: '1'

services:
        mysql:
                image: mysql:latest
                volumes:
                - ${PWD}/mysql:/var/lib/mysql
                ports:
                - "3306"
                container_name: "mysql-mosq"
		environment:
		- MYSQL_ROOT_PASSWORD=mypassword
                networks:
                - mosqnet

        mosquitto:
                build: .
                volumes:
                - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
                ports:
                - "1883:1883"
                - "9883:9883"
                networks:
                - mosqnet
                depends_on:
                - mysql
                labels:
                - "local.example.description=Mosquitto v1.4.10 MQTT server"


networks:
        mosqnet:

